import type { Metadata } from "next";
import "./globals.css";
import { App, ProgressBarProvider } from "@/components";
import { ThemeProvider } from "@/context/theme-context";

export const metadata: Metadata = {
  title: "DASHBOARD",
  description: "Generated by create next app",
};

const setInitialTheme = `
  (function() {
    try {
      const storedTheme = localStorage.getItem('theme');
      const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
      const theme = storedTheme || (prefersDark ? 'dark' : 'light');
      document.documentElement.classList.toggle('dark', theme === 'dark');
    } catch (_) {}
  })();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script dangerouslySetInnerHTML={{ __html: setInitialTheme }} />
      </head>
      <body>
        <ProgressBarProvider />
        <ThemeProvider>
          <App>{children}</App>
        </ThemeProvider>
      </body>
    </html>
  );
}
